name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install datamesh

      - name: Run Data Contract Validation on all examples
        run: |
          set -o pipefail
          failed_files=""
          for file in examples/all/*.yaml; do
            echo "Validating $file..."
            if ! data-contract-validation "$file"; then
              echo "Validation failed for $file"
              failed_files="$failed_files $file"
            fi
          done

          if [ -n "$failed_files" ]; then
            echo "Validation failed for the following files:$failed_files"
            exit 1
          else
            echo "All files validated successfully."
          fi

      - name: Validation Success
        run: echo "All validations passed successfully!"
